<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BookshopApp.Db\BookshopApp.Db.csproj" />
    <ProjectReference Include="..\BookshopApp.Models\BookshopApp.Models.csproj" />
  </ItemGroup>
</Project>